#!/usr/bin/env python3
"""
MySQL → PostgreSQL migration for Mercado Franquia.

Reads ~/franchise_db_dump.sql (mysqldump --extended-insert=FALSE) and:
  1. Drops any existing tables (new PascalCase names + old `franchises`).
  2. Creates 20 tables with hand-converted Postgres DDL.
  3. Creates supporting indexes.
  4. Parses every `INSERT INTO "TableName" ...` from the dump (MySQL uses
     backticks; we rewrite on the fly), converting
     MySQL literal/escape conventions to Python objects, then inserts through
     psycopg using parameter binding (safe against quoting bugs).
  5. Resets IDENTITY sequences on the four integer-PK tables.
  6. Prints row counts per table.

Usage (on the EC2, inside the venv):
    pip install 'psycopg[binary]>=3.1' sqlparse
    python migrate.py                            # uses defaults below
    python migrate.py --dump /path/to/dump.sql   # override
    python migrate.py --dry-run                  # prints DDL only, no writes

Env:
    DATABASE_URL   postgresql://mf_user:...@localhost:5432/mercadofranquia
    DUMP_PATH      /home/ubuntu/franchise_db_dump.sql
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterator

try:
    import psycopg
except ImportError as e:
    sys.exit("Missing dependency: pip install 'psycopg[binary]>=3.1' sqlparse")

try:
    import sqlparse
except ImportError:
    sys.exit("Missing dependency: pip install sqlparse")


DEFAULT_DB_URL = "postgresql://mf_user:mf_senha_forte_2026@localhost:5432/mercadofranquia"
DEFAULT_DUMP = "/home/ubuntu/franchise_db_dump.sql"


# ---------------------------------------------------------------------------
# DDL — hand-converted from the dump. Order matters: FK targets before FKs.
# ---------------------------------------------------------------------------

DDL: list[tuple[str, str]] = [
    # ---- Tables with no outgoing FKs first ----
    ("User", """
CREATE TABLE "User" (
    id              VARCHAR(191) PRIMARY KEY,
    name            VARCHAR(191) NOT NULL,
    email           VARCHAR(191) NOT NULL,
    password        VARCHAR(191) NOT NULL,
    role            VARCHAR(20)  NOT NULL DEFAULT 'MEMBER'
                    CHECK (role IN ('ADMIN','FRANCHISOR','FRANCHISEE','CANDIDATE','ENTHUSIAST','MEMBER')),
    "isActive"      BOOLEAN      NOT NULL DEFAULT TRUE,
    "createdAt"     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"     TIMESTAMP(3) NOT NULL,
    cpf             VARCHAR(191),
    phone           VARCHAR(191) NOT NULL,
    CONSTRAINT "User_email_key" UNIQUE (email),
    CONSTRAINT "User_phone_key" UNIQUE (phone),
    CONSTRAINT "User_cpf_key"   UNIQUE (cpf)
);
"""),

    ("ContactInfo", """
CREATE TABLE "ContactInfo" (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone    VARCHAR(191) NOT NULL,
    email    VARCHAR(191) NOT NULL,
    website  TEXT
);
"""),

    ("News", """
CREATE TABLE "News" (
    id          VARCHAR(191) PRIMARY KEY,
    title       TEXT         NOT NULL,
    category    VARCHAR(191) NOT NULL,
    summary     TEXT         NOT NULL,
    content     TEXT         NOT NULL,
    "photoUrl"  VARCHAR(191),
    "isActive"  BOOLEAN      NOT NULL DEFAULT TRUE,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL
);
"""),

    ("PlatformStatistics", """
CREATE TABLE "PlatformStatistics" (
    id                   INTEGER      NOT NULL DEFAULT 1 PRIMARY KEY,
    "franchisesReviewed" INTEGER      NOT NULL DEFAULT 0,
    "totalReviews"       INTEGER      NOT NULL DEFAULT 0,
    "totalSegments"      INTEGER      NOT NULL DEFAULT 0,
    "medianRating"       DOUBLE PRECISION,
    "updatedAt"          TIMESTAMP(3) NOT NULL
);
"""),

    ("RankingBugnumber", """
CREATE TABLE "RankingBugnumber" (
    id                 VARCHAR(191) PRIMARY KEY,
    name               VARCHAR(191) NOT NULL,
    position           INTEGER      NOT NULL,
    "growthPercentage" NUMERIC(5,2) NOT NULL,
    "isWorst"          BOOLEAN      NOT NULL DEFAULT FALSE,
    "isHidden"         BOOLEAN      NOT NULL DEFAULT FALSE,
    year               INTEGER      NOT NULL,
    "createdAt"        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"        TIMESTAMP(3) NOT NULL,
    CONSTRAINT "RankingBugnumber_year_position_key" UNIQUE (year, position)
);
"""),

    ("AbfSegmentEntry", """
CREATE TABLE "AbfSegmentEntry" (
    id          VARCHAR(191) PRIMARY KEY,
    year        INTEGER      NOT NULL,
    quarter     VARCHAR(2)   NOT NULL,
    segment     VARCHAR(191) NOT NULL,
    acronym     VARCHAR(10)  NOT NULL,
    value       INTEGER      NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "AbfSegmentEntry_year_quarter_acronym_key" UNIQUE (year, quarter, acronym)
);
"""),

    ("UserVerification", """
CREATE TABLE "UserVerification" (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(191) NOT NULL,
    code        VARCHAR(6)   NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "isUsed"    BOOLEAN      NOT NULL DEFAULT FALSE,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "usedAt"    TIMESTAMP(3),
    "userData"  TEXT
);
"""),

    # ---- Tables with FKs ----
    ("Franchise", """
CREATE TABLE "Franchise" (
    id                          VARCHAR(191) PRIMARY KEY,
    name                        VARCHAR(191) NOT NULL,
    sku                         VARCHAR(191),
    slug                        VARCHAR(191),
    "headquarterState"          VARCHAR(191),
    segment                     VARCHAR(191),
    subsegment                  VARCHAR(191),
    "businessType"              TEXT,
    "franchiseStartYear"        INTEGER,
    "abfSince"                  INTEGER,
    "videoUrl"                  TEXT,
    "updatedAt"                 TIMESTAMP(3) NOT NULL,
    "createdAt"                 TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "contactId"                 INTEGER,
    "ownerId"                   VARCHAR(191),
    "isActive"                  BOOLEAN      NOT NULL DEFAULT TRUE,
    "brandFoundationYear"       INTEGER,
    description                 TEXT,
    "detailedDescription"       TEXT,
    headquarter                 VARCHAR(191),
    "isAbfAssociated"           BOOLEAN,
    "logoUrl"                   VARCHAR(191),
    "totalUnits"                INTEGER,
    "totalUnitsInBrazil"        INTEGER,
    "thumbnailUrl"              VARCHAR(191),
    "lastScrapedAt"             TIMESTAMP(3),
    "scrapedWebsite"            VARCHAR(191),
    "calculationBaseAdFee"      VARCHAR(191),
    "calculationBaseRoyaltie"   VARCHAR(191),
    "galleryUrls"               TEXT,
    "isReview"                  BOOLEAN      NOT NULL DEFAULT TRUE,
    "averageRating"             DOUBLE PRECISION,
    "ratingSum"                 INTEGER      NOT NULL DEFAULT 0,
    "reviewCount"               INTEGER      NOT NULL DEFAULT 0,
    "unitsEvolution"            VARCHAR(10)  CHECK ("unitsEvolution" IN ('UP','DOWN','MAINTAIN')),
    "favoritesCount"            INTEGER      NOT NULL DEFAULT 0,
    "isSponsored"               BOOLEAN      NOT NULL DEFAULT FALSE,
    "sponsorPlacements"         JSONB        NOT NULL,
    "minimumInvestment"         NUMERIC(15,2),
    "maximumInvestment"         NUMERIC(15,2),
    "minimumReturnOnInvestment" INTEGER,
    "maximumReturnOnInvestment" INTEGER,
    "franchiseFee"              NUMERIC(15,2),
    "averageMonthlyRevenue"     NUMERIC(15,2),
    royalties                   NUMERIC(5,2),
    "advertisingFee"            NUMERIC(5,2),
    "setupCapital"              NUMERIC(15,2),
    "workingCapital"            NUMERIC(15,2),
    "storeArea"                 INTEGER,
    CONSTRAINT "Franchise_slug_key"      UNIQUE (slug),
    CONSTRAINT "Franchise_contactId_key" UNIQUE ("contactId"),
    CONSTRAINT "Franchise_contactId_fkey" FOREIGN KEY ("contactId") REFERENCES "ContactInfo"(id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Franchise_ownerId_fkey"   FOREIGN KEY ("ownerId")   REFERENCES "User"(id)
        ON DELETE CASCADE ON UPDATE CASCADE
);
"""),

    ("UserProfile", """
CREATE TABLE "UserProfile" (
    id                 VARCHAR(191) PRIMARY KEY,
    "userId"           VARCHAR(191) NOT NULL,
    city               VARCHAR(191) NOT NULL,
    "interestSectors"  VARCHAR(191) NOT NULL,
    "interestRegion"   VARCHAR(191) NOT NULL,
    "investmentRange"  VARCHAR(191) NOT NULL,
    CONSTRAINT "UserProfile_userId_key"  UNIQUE ("userId"),
    CONSTRAINT "UserProfile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"(id)
        ON DELETE CASCADE ON UPDATE CASCADE
);
"""),

    ("QuizSubmission", """
CREATE TABLE "QuizSubmission" (
    id          VARCHAR(191) PRIMARY KEY,
    "userId"    VARCHAR(191) NOT NULL,
    answers     TEXT         NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "QuizSubmission_userId_key"  UNIQUE ("userId"),
    CONSTRAINT "QuizSubmission_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"(id)
        ON DELETE CASCADE ON UPDATE CASCADE
);
"""),

    ("Notification", """
CREATE TABLE "Notification" (
    id          VARCHAR(191) PRIMARY KEY,
    "userId"    VARCHAR(191) NOT NULL,
    title       VARCHAR(191) NOT NULL,
    message     TEXT         NOT NULL,
    type        VARCHAR(30)  NOT NULL
                CHECK (type IN ('MEMBER_REGISTRATION','FRANCHISOR_REQUEST','REQUEST_APPROVED','REQUEST_REJECTED','SYSTEM')),
    link        VARCHAR(191),
    "isRead"    BOOLEAN      NOT NULL DEFAULT FALSE,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "readAt"    TIMESTAMP(3),
    CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"(id)
        ON DELETE CASCADE ON UPDATE CASCADE
);
"""),

    ("FranchisorUser", """
CREATE TABLE "FranchisorUser" (
    id                   VARCHAR(191) PRIMARY KEY,
    "streamName"         VARCHAR(191) NOT NULL,
    "userId"             VARCHAR(191) NOT NULL,
    cnpj                 VARCHAR(191) NOT NULL,
    responsable          VARCHAR(191) NOT NULL,
    "responsableRole"    VARCHAR(191) NOT NULL,
    "commercialEmail"    VARCHAR(191) NOT NULL,
    "commercialPhone"    VARCHAR(191) NOT NULL,
    "createdAt"          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"          TIMESTAMP(3) NOT NULL,
    "cnpjCardPath"       VARCHAR(191),
    "socialContractPath" VARCHAR(191) NOT NULL,
    CONSTRAINT "FranchisorUser_userId_key" UNIQUE ("userId"),
    CONSTRAINT "FranchisorUser_cnpj_key"   UNIQUE (cnpj),
    CONSTRAINT "FranchisorUser_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"(id)
        ON DELETE CASCADE ON UPDATE CASCADE
);
"""),

    ("FranchisorRequest", """
CREATE TABLE "FranchisorRequest" (
    id                    VARCHAR(191) PRIMARY KEY,
    "userId"              VARCHAR(191) NOT NULL,
    "streamName"          VARCHAR(191) NOT NULL,
    cnpj                  VARCHAR(191) NOT NULL,
    "cnpjCardPath"        VARCHAR(191) NOT NULL,
    "socialContractPath"  VARCHAR(191) NOT NULL,
    responsable           VARCHAR(191) NOT NULL,
    "responsableRole"     VARCHAR(191) NOT NULL,
    "commercialEmail"     VARCHAR(191) NOT NULL,
    "commercialPhone"     VARCHAR(191) NOT NULL,
    status                VARCHAR(20)  NOT NULL DEFAULT 'PENDING'
                          CHECK (status IN ('PENDING','APPROVED','REJECTED','UNDER_REVIEW')),
    "rejectionReason"     TEXT,
    "reviewedBy"          VARCHAR(191),
    "reviewedAt"          TIMESTAMP(3),
    "createdAt"           TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"           TIMESTAMP(3) NOT NULL,
    CONSTRAINT "FranchisorRequest_userId_key" UNIQUE ("userId"),
    CONSTRAINT "FranchisorRequest_cnpj_key"   UNIQUE (cnpj),
    CONSTRAINT "FranchisorRequest_userId_fkey"     FOREIGN KEY ("userId")     REFERENCES "User"(id)
        ON DELETE CASCADE  ON UPDATE CASCADE,
    CONSTRAINT "FranchisorRequest_reviewedBy_fkey" FOREIGN KEY ("reviewedBy") REFERENCES "User"(id)
        ON DELETE SET NULL ON UPDATE CASCADE
);
"""),

    ("NewsComment", """
CREATE TABLE "NewsComment" (
    id          VARCHAR(191) PRIMARY KEY,
    content     TEXT         NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "newsId"    VARCHAR(191) NOT NULL,
    "authorId"  VARCHAR(191) NOT NULL,
    CONSTRAINT "NewsComment_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"(id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "NewsComment_newsId_fkey"   FOREIGN KEY ("newsId")   REFERENCES "News"(id)
        ON DELETE CASCADE ON UPDATE CASCADE
);
"""),

    ("Favorite", """
CREATE TABLE "Favorite" (
    id            VARCHAR(191) PRIMARY KEY,
    "userId"      VARCHAR(191) NOT NULL,
    "franchiseId" VARCHAR(191) NOT NULL,
    "createdAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Favorite_userId_franchiseId_key" UNIQUE ("userId","franchiseId"),
    CONSTRAINT "Favorite_userId_fkey"      FOREIGN KEY ("userId")      REFERENCES "User"(id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Favorite_franchiseId_fkey" FOREIGN KEY ("franchiseId") REFERENCES "Franchise"(id)
        ON DELETE CASCADE ON UPDATE CASCADE
);
"""),

    ("BusinessModel", """
CREATE TABLE "BusinessModel" (
    id            VARCHAR(191) PRIMARY KEY,
    name          VARCHAR(191) NOT NULL,
    description   TEXT         NOT NULL,
    "photoUrl"    VARCHAR(191) NOT NULL,
    "franchiseId" VARCHAR(191) NOT NULL,
    "createdAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"   TIMESTAMP(3) NOT NULL,
    CONSTRAINT "BusinessModel_franchiseId_fkey" FOREIGN KEY ("franchiseId") REFERENCES "Franchise"(id)
        ON DELETE CASCADE ON UPDATE CASCADE
);
"""),

    ("FranchiseMonthlyUnits", """
CREATE TABLE "FranchiseMonthlyUnits" (
    id            VARCHAR(191) PRIMARY KEY,
    "franchiseId" VARCHAR(191) NOT NULL,
    period        TIMESTAMP(3) NOT NULL,
    units         INTEGER,
    "collectedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source        VARCHAR(191),
    CONSTRAINT "FranchiseMonthlyUnits_franchiseId_period_key" UNIQUE ("franchiseId", period),
    CONSTRAINT "FranchiseMonthlyUnits_franchiseId_fkey" FOREIGN KEY ("franchiseId") REFERENCES "Franchise"(id)
        ON DELETE CASCADE ON UPDATE CASCADE
);
"""),

    ("Review", """
CREATE TABLE "Review" (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anonymous      BOOLEAN      NOT NULL,
    rating         INTEGER      NOT NULL,
    comment        TEXT         NOT NULL,
    "createdAt"    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "franchiseId"  VARCHAR(191) NOT NULL,
    "isActive"     BOOLEAN      NOT NULL DEFAULT TRUE,
    "isFranchisee" BOOLEAN      NOT NULL DEFAULT FALSE,
    "authorId"     VARCHAR(191) NOT NULL,
    CONSTRAINT "Review_authorId_fkey"    FOREIGN KEY ("authorId")    REFERENCES "User"(id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Review_franchiseId_fkey" FOREIGN KEY ("franchiseId") REFERENCES "Franchise"(id)
        ON DELETE CASCADE ON UPDATE CASCADE
);
"""),

    ("ReviewResponse", """
CREATE TABLE "ReviewResponse" (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content     TEXT         NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "reviewId"  INTEGER      NOT NULL,
    "authorId"  VARCHAR(191) NOT NULL,
    CONSTRAINT "ReviewResponse_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"(id)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "ReviewResponse_reviewId_fkey" FOREIGN KEY ("reviewId") REFERENCES "Review"(id)
        ON DELETE CASCADE  ON UPDATE CASCADE
);
"""),

    ("_FranchiseFranchisees", """
CREATE TABLE "_FranchiseFranchisees" (
    "A" VARCHAR(191) NOT NULL,
    "B" VARCHAR(191) NOT NULL,
    CONSTRAINT "_FranchiseFranchisees_AB_unique" UNIQUE ("A","B"),
    CONSTRAINT "_FranchiseFranchisees_A_fkey" FOREIGN KEY ("A") REFERENCES "Franchise"(id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "_FranchiseFranchisees_B_fkey" FOREIGN KEY ("B") REFERENCES "User"(id)
        ON DELETE CASCADE ON UPDATE CASCADE
);
"""),
]

# Non-unique supporting indexes (unique ones are in-line constraints above).
INDEXES: list[str] = [
    'CREATE INDEX "AbfSegmentEntry_year_quarter_idx" ON "AbfSegmentEntry"(year, quarter);',
    'CREATE INDEX "BusinessModel_franchiseId_idx"    ON "BusinessModel"("franchiseId");',
    'CREATE INDEX "Favorite_userId_idx"              ON "Favorite"("userId");',
    'CREATE INDEX "Favorite_franchiseId_idx"         ON "Favorite"("franchiseId");',
    'CREATE INDEX "Franchise_segment_idx"                      ON "Franchise"(segment);',
    'CREATE INDEX "Franchise_slug_idx"                         ON "Franchise"(slug);',
    'CREATE INDEX "Franchise_totalUnits_idx"                   ON "Franchise"("totalUnits");',
    'CREATE INDEX "Franchise_averageRating_idx"                ON "Franchise"("averageRating");',
    'CREATE INDEX "Franchise_minimumInvestment_idx"            ON "Franchise"("minimumInvestment");',
    'CREATE INDEX "Franchise_maximumInvestment_idx"            ON "Franchise"("maximumInvestment");',
    'CREATE INDEX "Franchise_franchiseFee_idx"                 ON "Franchise"("franchiseFee");',
    'CREATE INDEX "Franchise_averageMonthlyRevenue_idx"        ON "Franchise"("averageMonthlyRevenue");',
    'CREATE INDEX "Franchise_minimumReturnOnInvestment_idx"    ON "Franchise"("minimumReturnOnInvestment");',
    'CREATE INDEX "Franchise_isActive_idx"                     ON "Franchise"("isActive");',
    'CREATE INDEX "Franchise_isActive_segment_idx"             ON "Franchise"("isActive", segment);',
    'CREATE INDEX "Franchise_isActive_totalUnits_idx"          ON "Franchise"("isActive", "totalUnits");',
    'CREATE INDEX "Franchise_isSponsored_idx"                  ON "Franchise"("isSponsored");',
    'CREATE INDEX "Franchise_isActive_isSponsored_idx"         ON "Franchise"("isActive", "isSponsored");',
    'CREATE INDEX "Franchise_ownerId_fkey"                     ON "Franchise"("ownerId");',
    'CREATE INDEX "FranchiseMonthlyUnits_period_franchiseId_idx" ON "FranchiseMonthlyUnits"(period, "franchiseId");',
    'CREATE INDEX "FranchiseMonthlyUnits_franchiseId_period_idx" ON "FranchiseMonthlyUnits"("franchiseId", period);',
    'CREATE INDEX "FranchisorRequest_status_idx"      ON "FranchisorRequest"(status);',
    'CREATE INDEX "FranchisorRequest_userId_idx"      ON "FranchisorRequest"("userId");',
    'CREATE INDEX "FranchisorRequest_reviewedBy_fkey" ON "FranchisorRequest"("reviewedBy");',
    'CREATE INDEX "NewsComment_newsId_idx"   ON "NewsComment"("newsId");',
    'CREATE INDEX "NewsComment_authorId_idx" ON "NewsComment"("authorId");',
    'CREATE INDEX "Notification_userId_idx"        ON "Notification"("userId");',
    'CREATE INDEX "Notification_userId_isRead_idx" ON "Notification"("userId", "isRead");',
    'CREATE INDEX "Notification_createdAt_idx"     ON "Notification"("createdAt");',
    'CREATE INDEX "RankingBugnumber_year_idx"        ON "RankingBugnumber"(year);',
    'CREATE INDEX "Review_authorId_fkey"    ON "Review"("authorId");',
    'CREATE INDEX "Review_franchiseId_fkey" ON "Review"("franchiseId");',
    'CREATE INDEX "ReviewResponse_authorId_fkey" ON "ReviewResponse"("authorId");',
    'CREATE INDEX "ReviewResponse_reviewId_fkey" ON "ReviewResponse"("reviewId");',
    'CREATE INDEX "_FranchiseFranchisees_B_index" ON "_FranchiseFranchisees"("B");',
]

# Columns stored as BOOLEAN in Postgres (were tinyint(1) in MySQL).
# Values 0/1 in the dump need rewriting to FALSE/TRUE during load.
BOOLEAN_COLUMNS: dict[str, set[str]] = {
    "User":             {"isActive"},
    "News":             {"isActive"},
    "Notification":     {"isRead"},
    "RankingBugnumber": {"isWorst", "isHidden"},
    "Review":           {"anonymous", "isActive", "isFranchisee"},
    "UserVerification": {"isUsed"},
    "Franchise":        {"isActive", "isAbfAssociated", "isReview", "isSponsored"},
}

# Columns stored as JSONB — MySQL emits them as normal strings; psycopg handles str→jsonb.
JSON_COLUMNS: dict[str, set[str]] = {
    "Franchise": {"sponsorPlacements"},
}

# Tables with integer IDENTITY PKs — sequences need resetting after load.
SEQUENCE_TABLES: list[tuple[str, str]] = [
    ("ContactInfo",      "id"),
    ("Review",           "id"),
    ("ReviewResponse",   "id"),
    ("UserVerification", "id"),
]

# Legacy table names that may exist from earlier manual setup — dropped at start.
LEGACY_TABLES = ["franchises"]


# ---------------------------------------------------------------------------
# MySQL INSERT parser
# ---------------------------------------------------------------------------

INSERT_RE = re.compile(
    r"^INSERT\s+INTO\s+`(?P<table>\w+)`\s*\((?P<cols>[^)]+)\)\s*VALUES\s*\((?P<vals>.*)\)\s*;?\s*$",
    re.DOTALL | re.IGNORECASE,
)


def parse_values_tuple(s: str) -> list[str]:
    """
    Split a VALUES row like: "'abc','def',NULL,42,0.5"
    into raw token strings (strings keep their surrounding quotes).
    Respects MySQL-style escapes inside strings: \\', \\\\, ''.
    """
    tokens: list[str] = []
    i, n = 0, len(s)
    while i < n:
        while i < n and s[i] in " \t\n\r":
            i += 1
        if i >= n:
            break
        if s[i] == "'":
            # Scan closing quote, handling escapes
            j = i + 1
            while j < n:
                c = s[j]
                if c == "\\" and j + 1 < n:
                    j += 2
                    continue
                if c == "'":
                    if j + 1 < n and s[j + 1] == "'":
                        j += 2
                        continue
                    break
                j += 1
            if j >= n:
                raise ValueError(f"unterminated string at {i}: {s[i:i+40]!r}")
            tokens.append(s[i : j + 1])
            i = j + 1
        else:
            j = i
            depth = 0
            while j < n:
                c = s[j]
                if c == "," and depth == 0:
                    break
                if c == "(":
                    depth += 1
                elif c == ")":
                    depth -= 1
                j += 1
            tokens.append(s[i:j].strip())
            i = j
        # Skip the comma
        if i < n and s[i] == ",":
            i += 1
    return tokens


def mysql_unescape_string(lit: str) -> str:
    """Convert a MySQL string literal (with surrounding ') to a Python str."""
    assert lit.startswith("'") and lit.endswith("'"), f"not a string literal: {lit[:40]!r}"
    inner = lit[1:-1]
    out: list[str] = []
    i, n = 0, len(inner)
    while i < n:
        c = inner[i]
        if c == "\\" and i + 1 < n:
            nxt = inner[i + 1]
            escapes = {
                "n": "\n", "t": "\t", "r": "\r", "0": "\x00",
                "Z": "\x1a", "b": "\b", "\\": "\\", "'": "'", '"': '"',
            }
            out.append(escapes.get(nxt, nxt))
            i += 2
        elif c == "'" and i + 1 < n and inner[i + 1] == "'":
            out.append("'")
            i += 2
        else:
            out.append(c)
            i += 1
    return "".join(out)


def mysql_literal_to_python(tok: str) -> Any:
    """Convert a single MySQL VALUES token to a Python value."""
    tok = tok.strip()
    if not tok:
        return None
    if tok.upper() == "NULL":
        return None
    if tok.startswith("'"):
        return mysql_unescape_string(tok)
    if tok.startswith(("0x", "0X")) and all(c in "0123456789abcdefABCDEF" for c in tok[2:]):
        return bytes.fromhex(tok[2:])
    # Numeric
    if re.fullmatch(r"-?\d+", tok):
        return int(tok)
    if re.fullmatch(r"-?\d+\.\d*", tok) or re.fullmatch(r"-?\.\d+", tok):
        return float(tok)
    # Scientific or unexpected — pass through as str
    return tok


@dataclass
class ParsedInsert:
    table: str
    columns: list[str]
    values: list[Any]


def parse_insert(stmt: str) -> ParsedInsert | None:
    """Parse a single INSERT statement from the mysqldump."""
    m = INSERT_RE.match(stmt)
    if not m:
        return None
    table = m.group("table")
    cols = [c.strip().strip("`") for c in m.group("cols").split(",")]
    raw_vals = parse_values_tuple(m.group("vals"))
    if len(raw_vals) != len(cols):
        raise ValueError(
            f"column/value count mismatch for {table}: "
            f"{len(cols)} cols vs {len(raw_vals)} values"
        )
    bool_cols = BOOLEAN_COLUMNS.get(table, set())
    python_vals: list[Any] = []
    for col, raw in zip(cols, raw_vals):
        val = mysql_literal_to_python(raw)
        if col in bool_cols:
            if val is None:
                python_vals.append(None)
            elif isinstance(val, int):
                python_vals.append(bool(val))
            elif isinstance(val, str) and val in ("0", "1"):
                python_vals.append(val == "1")
            else:
                python_vals.append(bool(val))
        else:
            python_vals.append(val)
    return ParsedInsert(table=table, columns=cols, values=python_vals)


def iter_inserts(dump_path: Path) -> Iterator[ParsedInsert]:
    """Yield parsed INSERTs in dump order."""
    with dump_path.open("r", encoding="utf-8", errors="replace") as f:
        sql = f.read()
    for raw in sqlparse.split(sql):
        stmt = raw.strip()
        if not stmt.upper().startswith("INSERT INTO"):
            continue
        parsed = parse_insert(stmt)
        if parsed:
            yield parsed


# ---------------------------------------------------------------------------
# Migration
# ---------------------------------------------------------------------------

def qident(name: str) -> str:
    """Quote an identifier for Postgres."""
    return '"' + name.replace('"', '""') + '"'


def drop_all(cur) -> None:
    all_tables = [name for name, _ in DDL] + LEGACY_TABLES
    for t in reversed(all_tables):
        cur.execute(f'DROP TABLE IF EXISTS {qident(t)} CASCADE;')
        print(f"  DROP  {t}")


def create_all(cur) -> None:
    for name, ddl in DDL:
        cur.execute(ddl)
        print(f"  CREATE  {name}")
    for idx in INDEXES:
        cur.execute(idx)
    print(f"  +{len(INDEXES)} indexes")


def load_data(cur, dump_path: Path) -> dict[str, int]:
    """
    Insert data in the order rows appear in the dump (which matches FK-safe
    ordering because mysqldump emits them alphabetically but we respect
    the --extended-insert=FALSE stream; for safety we defer FK checks).
    """
    # Disable triggers (FKs) during bulk load, then re-enable. Session-level.
    cur.execute("SET session_replication_role = 'replica';")

    counts: dict[str, int] = {}
    batch: dict[str, tuple[list[str], list[tuple]]] = {}
    BATCH_SIZE = 500

    def flush_batch(table: str) -> None:
        cols, rows = batch[table]
        if not rows:
            return
        placeholders = ", ".join(["%s"] * len(cols))
        col_sql = ", ".join(qident(c) for c in cols)
        sql = f'INSERT INTO {qident(table)} ({col_sql}) VALUES ({placeholders})'
        cur.executemany(sql, rows)
        counts[table] = counts.get(table, 0) + len(rows)
        batch[table] = (cols, [])

    for parsed in iter_inserts(dump_path):
        if parsed.table not in batch:
            batch[parsed.table] = (parsed.columns, [])
        else:
            # Column order could technically vary per-statement; assert same shape.
            assert batch[parsed.table][0] == parsed.columns, (
                f"column order mismatch within {parsed.table}"
            )
        batch[parsed.table][1].append(tuple(parsed.values))
        if len(batch[parsed.table][1]) >= BATCH_SIZE:
            flush_batch(parsed.table)

    for table in list(batch.keys()):
        flush_batch(table)

    cur.execute("SET session_replication_role = 'origin';")
    return counts


def reset_sequences(cur) -> None:
    for table, col in SEQUENCE_TABLES:
        cur.execute(
            f"""
            SELECT setval(
                pg_get_serial_sequence(%s, %s),
                COALESCE((SELECT MAX({qident(col)}) FROM {qident(table)}), 0) + 1,
                false
            );
            """,
            (qident(table), col),
        )
        print(f"  SEQ    {table}.{col}")


def report(cur) -> None:
    print("\n=== Row counts (PostgreSQL) ===")
    total = 0
    for name, _ in DDL:
        cur.execute(f"SELECT COUNT(*) FROM {qident(name)};")
        c = cur.fetchone()[0]
        total += c
        print(f"  {name:<24} {c:>6}")
    print(f"  {'TOTAL':<24} {total:>6}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dump", default=os.environ.get("DUMP_PATH", DEFAULT_DUMP))
    parser.add_argument("--db",   default=os.environ.get("DATABASE_URL", DEFAULT_DB_URL))
    parser.add_argument("--dry-run", action="store_true", help="Print DDL only, don't execute")
    args = parser.parse_args()

    dump_path = Path(args.dump).expanduser()
    if not dump_path.exists():
        sys.exit(f"Dump not found: {dump_path}")

    if args.dry_run:
        print("=== DDL (dry-run) ===")
        for name, ddl in DDL:
            print(f"-- {name}")
            print(ddl.strip(), "\n")
        for idx in INDEXES:
            print(idx)
        return

    print(f"Dump:  {dump_path}  ({dump_path.stat().st_size / 1024:.1f} KB)")
    print(f"DB:    {args.db}")
    print()

    with psycopg.connect(args.db, autocommit=False) as conn:
        with conn.cursor() as cur:
            print("-- Dropping existing tables --")
            drop_all(cur)
            print("\n-- Creating schema --")
            create_all(cur)
            print("\n-- Loading data --")
            counts = load_data(cur, dump_path)
            print("\n-- Resetting sequences --")
            reset_sequences(cur)
        conn.commit()
        print("\nCOMMIT OK.")

    with psycopg.connect(args.db) as conn:
        with conn.cursor() as cur:
            report(cur)

    # Sanity check: the loaded counts should match what COUNT(*) sees.
    print("\n=== Inserts parsed from dump ===")
    for t, c in sorted(counts.items()):
        print(f"  {t:<24} {c:>6}")


if __name__ == "__main__":
    main()
