"""sprint 3: add profileType to User and create AdminActionLog

Revision ID: 1d52f2c66760
Revises: d79fa11f4e24
Create Date: 2026-04-21 14:50:41.027475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d52f2c66760'
down_revision: Union[str, Sequence[str], None] = 'd79fa11f4e24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AdminActionLog',
    sa.Column('id', sa.String(length=191), server_default=sa.text('CAST(gen_random_uuid() AS VARCHAR)'), nullable=False),
    sa.Column('adminId', sa.String(length=191), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('targetUserId', sa.String(length=191), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['adminId'], ['User.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['targetUserId'], ['User.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_admin_action_log_created', 'AdminActionLog', ['createdAt'], unique=False)
    op.create_index('idx_admin_action_log_target', 'AdminActionLog', ['targetUserId'], unique=False)
    # Cria o tipo enum ProfileType primeiro (necessário antes do ADD COLUMN)
    profile_type_enum = postgresql.ENUM('INVESTOR', 'FRANCHISOR', name='ProfileType', create_type=False)
    profile_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('User', sa.Column('profileType', profile_type_enum, server_default='INVESTOR', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'profileType')
    op.drop_index('idx_admin_action_log_target', table_name='AdminActionLog')
    op.drop_index('idx_admin_action_log_created', table_name='AdminActionLog')
    op.drop_table('AdminActionLog')
    profile_type_enum = postgresql.ENUM('INVESTOR', 'FRANCHISOR', name='ProfileType', create_type=False)
    profile_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
